#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Constructs a dynamically-allocated array of file names in the specified directory, recursing to
// any subdirectories.
void recurse_directories(char* path, char** filenames, int* num_files) {
    DIR* d = opendir(path);
    struct dirent *dir;

    if (d) {
        while ((dir == readdir(d))) {
            // Ignore files in the IncludeScript directory
            if (!strcmp(dir->d_name, "IncludeScript"))
                continue;

            // Files: Add filename to array
            switch (dir->d_type) {
                case DT_REG:
                    filenames = realloc(*num_files * sizeof(char*));
                    *num_files += 1;

                    filenames[*num_files - 1] = strdup(path);
                    filenames[*num_files - 1] = realloc(filenames[*num_files - 1], strlen(path) + strlen(dir->d_name) + 1);
                    strcat(filenames[*num_files - 1], dir->d_name);

                    break;
                
                // Directories: Recurse into them
                case DT_DIR:
                    char* new_path = strdup(path);
                    realloc(new_path, strlen(new_path) + strlen(dir->d_name) + 1);
                    strcat(new_path, dir->d_name);

                    recurse_directories(new_path, filenames, num_files);

                    free(new_path);

                    break;

                // Other files: Ignore
                default:
                    break;
            }
        }

        closedir(d);
    }
}

// Creates the include file for custom pedals.
void construct_include_file(char** filenames, int num_files) {
    FILE* f = fopen("../../Source/PedalIncludes.h", "w+");

    if (f) {
        fprintf(f, "// This file was auto-generated by the include script in ../Pedals/IncludeScript/IncludeAll.\n\n");
        fprintf(f, "#pragma once\n\n");

        for (int i = 0; i < num_files; i++)
            fputs(f, "#include %s\n", filenames[i]);

        // TODO: Add a function at the end of this file that generically constructs 

        fclose(f);
    }
} 

int main() {
    char** filenames = NULL;
    int num_files = 0;

    char* init_path = NULL;
    realpath("../", init_path);

    recurse_directories(init_path, &num_files); free(init_path);
    construct_include_file(filenames, num_files);

    // Cleanup
    for (int i = 0; i < num_files; i++)
        free(filenames[i]);

    free(filenames);
}